### ISSUE TITLE
Separate testing code from features

### ISSUE THREAD

**Issue by yungyuc** [kevinshlo/CornerStitching#5]
You are keeping the testing code in the same file as the feature code, e.g., https://github.com/kevinshlo/CornerStitching/blob/29806cfee0ff3931ac505c03b8f706b63f3ce88d/src/tile.cpp#L23

It is hard to maintain.  Testing code should be separate from feature code.  Ideally the testing code can be manually turned on and off, e.g., https://github.com/solvcon/modmesh/blob/880ea79cb2f7f4dedec447e14a79d6ee1ca9c217/gtests/CMakeLists.txt#L1

But for the term project, it may not need to be so delicate.

**Comment by kevinshlo** [comment]
Thanks for the information. I currently use macro `GTEST` to enable/disable google-test compilation in the Makefile. I will add this information later.

**Comment by yungyuc** [comment]
Being hard to maintain differs from unable to maintain.  The latter is very hard to achieve.

Being someone who is very familiar with the code base, you can certainly use a macro in `Makefile` to control which test to run.  Those who are not familiar with your code will not be able to work in that way very quickly.
